apiVersion: v1
kind: Pod
metadata:
 name: pod1
 namespace: restore
 labels:
   app: pod1
spec:
 containers:
 - name: container1
   image: debian:buster-slim
   command: ["/bin/bash", "-c", "sleep infinity"]
---
apiVersion: v1
kind: Pod
metadata:
 name: pod2
 namespace: restore
 labels:
   app: pod2
spec:
 containers:
 - name: container1
   image: debian:buster-slim
   command: ["/bin/bash", "-c", "sleep infinity"]
