apiVersion: v1
kind: Pod
metadata:
 name: pod
 namespace: restore
spec:
 containers:
 - name: container1
   image: debian:buster-slim
   command: ["/bin/bash", "-c", "sleep infinity"]
 - name: container2
   image: debian:buster-slim
   command: ["/bin/bash", "-c", "sleep infinity"]
 - name: container3
   image: debian:buster-slim
   command: ["/bin/bash", "-c", "sleep infinity"]
