apiVersion: v1
kind: Pod
metadata:
  name: postgres
  namespace: restore
  annotations:
    backup.velero.io/backup-volumes: backup
spec:
  containers:
  - name: postgres
    image: postgres:12
    env:
    - name: POSTGRES_PASSWORD
      value: velero
    - name: POSTGRES_USER
      value: velero
    - name: POSTGRES_DB
      value: velero
    volumeMounts:
    - mountPath: /backup
      name: backup
  volumes:
  - name: backup
    emptyDir: {}
