apiVersion: v1
kind: Pod
metadata:
 name: pod
 namespace: restore
 annotations:
   "post.hook.restore.velero.io/container": "container1"
   "post.hook.restore.velero.io/command": '["/bin/bash", "-c", "echo hello2 > /world.txt"]'
spec:
 containers:
 - name: container1
   image: debian:buster-slim
   command: ["/bin/bash", "-c", "sleep infinity"]
