apiVersion: velero.io/v1
kind: Restore
metadata:
  name: restore-01-3pyy
  namespace: velero
spec:
  backupName: backup-01-3pyy
  includedNamespaces:
  - '*'
  includedResources:
  - '*'
  excludedResources:
  - storageclasses.storage.k8s.io
  includeClusterResources: null
  hooks:
    resources:
    - name: my-hook
      includedNamespaces:
      - '*'
      includedResources:
      - 'pods'
      postHooks:
      - exec:
          container: pod
          command:
          - /bin/bash
          - '-c'
          - 'echo hello > /world.txt'
